# avahi-autoipd
# Autogenerated from man page /usr/share/man/man8/avahi-autoipd.8.gz
# using Deroffing man parser
complete -c avahi-autoipd -s D -l daemonize --description 'Daemonize after startup.  Implies --syslog.'
complete -c avahi-autoipd -s k -l kill --description 'Kill an already running avahi-autoipd on the sp… [See Man Page]'
complete -c avahi-autoipd -s r -l refresh --description 'Tell an already running avahi-autoipd to re-ann… [See Man Page]'
complete -c avahi-autoipd -s c -l check --description 'Return 0 as return code if avahi-autoipd is alr… [See Man Page]'
complete -c avahi-autoipd -s s -l syslog --description 'Log to syslog instead of STDERR.  Implied by --daemonize.'
complete -c avahi-autoipd -l debug --description 'Enable verbose mode.'
complete -c avahi-autoipd -l no-drop-root --description 'Don\'t drop root privileges after startup.'
complete -c avahi-autoipd -l no-chroot --description 'Don\'t chroot(2) the daemon.'
complete -c avahi-autoipd -s S -l start --description 'Try to acquire the specified IP address, which … [See Man Page]'
complete -c avahi-autoipd -s w -l wait --description 'Wait until a IP address has been successfully a… [See Man Page]'
complete -c avahi-autoipd -l force-bind --description 'Acquire an IPv4LL address, even if a routable a… [See Man Page]'
complete -c avahi-autoipd -l no-proc-title --description 'Don\'t change the process name while running.'
complete -c avahi-autoipd -s h -l help --description 'Show help.'
complete -c avahi-autoipd -s v -l version --description 'Show version information.  FILES /etc/avahi/avahi-autoipd.'

