# bond2team
# Autogenerated from man page /usr/share/man/man1/bond2team.1.gz
# using Deroffing man parser
complete -c bond2team -l master --description 'Specify the interface name or ifcfg file to convert.'
complete -c bond2team -l rename --description 'This is a convenient option to replace the orig… [See Man Page]'
complete -c bond2team -l ifcfg --description 'Set the output format to ifcfg config style.  [default].'
complete -c bond2team -l json --description 'Set the output format to JSON style.  See  teamd.'
complete -c bond2team -l bonding_opts --description 'Specify the bonding options to be converted ins… [See Man Page]'
complete -c bond2team -l port --description 'Set the specified interface as a team port.'
complete -c bond2team -l configdir --description 'Change the ifcfg configuration path from \\%/etc… [See Man Page]'
complete -c bond2team -l outputdir --description 'Set the output directory to <directory>.'
complete -c bond2team -l stdout --description 'Print the result to the screen instead of writing to files.'
complete -c bond2team -l debug --description 'Increase the debugging level.'
complete -c bond2team -l quiet --description 'Disallow any messages to be printed to console.'
complete -c bond2team -l version --description 'Print tool version to console and exit.'
complete -c bond2team -l help --description 'Print help text to console and exit.'
complete -c bond2team -l examples --description 'Print common usage examples to console and exit.  EXAMPLES.'
complete -c bond2team -l 'examples.' --description 'CAVEATS.'

