# bridge
# Autogenerated from man page /usr/share/man/man8/bridge.8.gz
# using Deroffing man parser
complete -c bridge -s V -o Version --description 'print the version of the  bridge utility and exit.'
complete -c bridge -s s -o stats -o statistics --description 'output more information.'
complete -c bridge -s d -o details --description 'print detailed information about MDB router ports.'
complete -c bridge -s n -o net -o netns --description 'switches  bridge to the specified network namespace R NETNS .'
complete -c bridge -s b -o batch --description 'Read commands from provided file or standard in… [See Man Page]'
complete -c bridge -o force --description 'Don\'t terminate bridge command on errors in batch mode.'
complete -c bridge -o 'V[ersion]' --description '.'
complete -c bridge -o 's[tatistics]' --description '.'
complete -c bridge -o 'n[etns]' --description '.'
complete -c bridge -o 'b[atch]' --description '.'
complete -c bridge -o 'j[son]' --description 'bridge link set dev DEV  [  cost COST  ] [  pri… [See Man Page]'
complete -c bridge -o json --description 'Display results in JSON format.'
complete -c bridge -s t -o timestamp --description 'display current time when using monitor option.'

