# c_rehash
# Autogenerated from man page /usr/share/man/man1/c_rehash.1ssl.gz
# using Type1
complete -c c_rehash -o old --description 'Use old-style hashing (\\s-1MD5,\\s0 as opposed t… [See Man Page]'
complete -c c_rehash -s h --description 'Display a brief usage message.'
complete -c c_rehash -s n --description 'Do not remove existing links.'

