# chage
# Autogenerated from man page /usr/share/man/man1/chage.1.gz
# using Deroffing man parser
complete -c chage -s d -l lastdayLAST_DAY --description 'Set the number of days since January 1st, 1970 … [See Man Page]'
complete -c chage -s E -l expiredateEXPIRE_DATE --description 'Set the date or number of days since January 1,… [See Man Page]'
complete -c chage -s h -l help --description 'Display help message and exit.'
complete -c chage -s I -l inactiveINACTIVE --description 'Set the number of days of inactivity after a pa… [See Man Page]'
complete -c chage -s l -l list --description 'Show account aging information.'
complete -c chage -s m -l mindaysMIN_DAYS --description 'Set the minimum number of days between password… [See Man Page]'
complete -c chage -s M -l maxdaysMAX_DAYS --description 'Set the maximum number of days during which a p… [See Man Page]'
complete -c chage -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c chage -s W -l warndaysWARN_DAYS --description 'Set the number of days of warning before a pass… [See Man Page]'
complete -c chage -l lastday --description '.'
complete -c chage -l expiredate --description '.'
complete -c chage -s 1 --description 'as the EXPIRE_DATE will remove an account expiration date.'
complete -c chage -l inactive --description '.'
complete -c chage -l mindays --description '.'
complete -c chage -l maxdays --description '.'
complete -c chage -l root --description '.'
complete -c chage -l warndays --description '.'

