# coredumpctl
# Autogenerated from man page /usr/share/man/man1/coredumpctl.1.gz
# using Deroffing man parser
complete -c coredumpctl -s h -l help --description 'Print a short help text and exit.'
complete -c coredumpctl -l version --description 'Print a short version string and exit.'
complete -c coredumpctl -l no-legend --description 'Do not print column headers.'
complete -c coredumpctl -l no-pager --description 'Do not pipe output into a pager.'
complete -c coredumpctl -s 1 --description 'Show information of a single core dump only, in… [See Man Page]'
complete -c coredumpctl -s F -l field --description 'Print all possible data values the specified fi… [See Man Page]'
complete -c coredumpctl -s o -l output --description 'Write the core to FILE.'
complete -c coredumpctl -s D -l directory --description 'Use the journal files in the specified DIR.'

