# ctags
# Autogenerated from man page /usr/share/man/man1/ctags.1p.gz
# using Deroffing man parser
complete -c ctags -s a --description 'Append to tagsfile .'
complete -c ctags -s f --description 'Write the object locator lists into tagsfile in… [See Man Page]'
complete -c ctags -s x --description 'Produce a list of object names, the line number… [See Man Page]'
complete -c ctags -s F --description 'option was omitted as redundant, since it is the default.  The.'
complete -c ctags -s B --description 'option was omitted as being of very limited usefulness.  The.'
complete -c ctags -s t --description 'option was omitted since the recognition of typ… [See Man Page]'
complete -c ctags -s u --description 'option was omitted because the update function … [See Man Page]'
complete -c ctags -s w --description 'option to suppress warning diagnostics.'
complete -c ctags -s v --description 'If the.'

