# cups-genppd
# Autogenerated from man page /usr/share/man/man8/cups-genppd.8.gz
# using Deroffing man parser
complete -c cups-genppd -s c --description 'use localedir as the base directory for locale data.'
complete -c cups-genppd -s l --description 'output PPDs translated with messages for locale.'
complete -c cups-genppd -s p --description 'output PPDs in directory prefix.'
complete -c cups-genppd -s q --description 'Quiet mode.'
complete -c cups-genppd -s v --description 'Verbose mode.'
complete -c cups-genppd -s h --description 'show a help message.'
complete -c cups-genppd -s L --description 'list available translations (message catalogs).'
complete -c cups-genppd -s M --description 'list available printer models.'
complete -c cups-genppd -s V --description 'show version information and defaults The defau… [See Man Page]'

