# cups-browsed
# Autogenerated from man page /usr/share/man/man8/cups-browsed.8.gz
# using Deroffing man parser
complete -c cups-browsed -s v -s d -l debug --description 'Debug mode, verbose logging to stderr.'
complete -c cups-browsed -s l -l logfile --description 'Debug logging into /var/log/cups/cups-browsed_log file.'
complete -c cups-browsed -s c --description 'Uses the alternative configuration file config-… [See Man Page]'
complete -c cups-browsed -s o -s o --description 'Supply configuration options via the command line.'
complete -c cups-browsed -l autoshutdown --description 'Auto shutdown mode, mode is off for no auto shu… [See Man Page]'
complete -c cups-browsed -l autoshutdown-on --description 'What cups-browsed considers as inactivity for auto-shutdown.'
complete -c cups-browsed -l autoshutdown-timeout --description 'timeout tells after how many seconds cups-brows… [See Man Page]'
complete -c cups-browsed -s h -l help -l version --description 'Display usage and version info and do not start the daemon.'

