# dbus-update-activation-environment
# Autogenerated from man page /usr/share/man/man1/dbus-update-activation-environment.1.gz
# using Deroffing man parser
complete -c dbus-update-activation-environment -l all --description 'Set all environment variables present in the en… [See Man Page]'
complete -c dbus-update-activation-environment -l systemd --description 'Set environment variables for systemd user serv… [See Man Page]'
complete -c dbus-update-activation-environment -l verbose --description 'Output messages to standard error explaining wh… [See Man Page]'

