# derdump
# Autogenerated from man page /usr/share/man/man1/derdump.1.gz
# using Deroffing man parser
complete -c derdump -s r --description 'For formatted items, dump raw bytes as well.'
complete -c derdump -s i --description 'Define an input file to use (default is stdin).'
complete -c derdump -s o --description 'Define an output file to use (default is stdout).'

