# devlink-dev
# Autogenerated from man page /usr/share/man/man8/devlink-dev.8.gz
# using Deroffing man parser
complete -c devlink-dev -o 'V[ersion]' --description '.'
complete -c devlink-dev -o 'n[no-nice-names]' --description 'devlink dev show [  DEV  ] devlink dev help.'

