# devlink-port
# Autogenerated from man page /usr/share/man/man8/devlink-port.8.gz
# using Deroffing man parser
complete -c devlink-port -o 'V[ersion]' --description '.'
complete -c devlink-port -o 'n[no-nice-names]' --description 'devlink port set  DEV/PORT_INDEX [  type  {  et… [See Man Page]'

