# devlink
# Autogenerated from man page /usr/share/man/man8/devlink.8.gz
# using Deroffing man parser
complete -c devlink -s V -o Version --description 'Print the version of the  devlink utility and exit.'
complete -c devlink -s n -o no-nice-names --description 'Turn off printing out nice names, for example n… [See Man Page]'
complete -c devlink -o 'V[ersion]' --description '.'
complete -c devlink -o 'n[no-nice-names]' --description '.'

