# devlink-sb
# Autogenerated from man page /usr/share/man/man8/devlink-sb.8.gz
# using Deroffing man parser
complete -c devlink-sb -o 'V[ersion]' --description '.'
complete -c devlink-sb -o 'n[no-nice-names]' --description 'devlink sb show  [  DEV  [  sb SB_INDEX  ] ] de… [See Man Page]'

