# dvconnect
# Autogenerated from man page /usr/share/man/man1/dvconnect.1.gz
# using Deroffing man parser
complete -c dvconnect -l version --description 'show dvconnect version number.'
complete -c dvconnect -s s -l send --description 'send data instead of capturing.'
complete -c dvconnect -s v -l verbose --description 'show status information while receiving / sending.'
complete -c dvconnect -s c -l channel --description 'channel to send / receive on (range: 0 - 63, default = 63).'
complete -c dvconnect -s k -l kbuffers --description 'number of kernel video1394 frame buffers to use.  default = 8.'
complete -c dvconnect -l start-frame --description 'start at count frame (defaults to 0).'
complete -c dvconnect -s e -l end-frame --description 'end at count frame (defaults to unlimited).'
complete -c dvconnect -l cip-n-ntsc --description 'cip n ntsc timing counter (default: 2436).'
complete -c dvconnect -l cip-d-ntsc --description 'cip d ntsc timing counter (default: 38400).'
complete -c dvconnect -l syt-offset --description 'syt offset (default: 10000 range: 10000-26000).'
complete -c dvconnect -s b -l buffers --description 'max number of file io thread buffers to use.  default = 250.'
complete -c dvconnect -s u -l underrun-data --description 'file with the frame to send in case of underruns.'
complete -c dvconnect -s d -l device --description 'Specify the video1394 device (default /dev/video1394/0).'
complete -c dvconnect -s '?' -l help --description 'Show help message.'
complete -c dvconnect -l usage --description 'Display brief usage message.'

