# e2undo
# Autogenerated from man page /usr/share/man/man8/e2undo.8.gz
# using Deroffing man parser
complete -c e2undo -s f --description 'Normally,  e2undo will check the filesystem sup… [See Man Page]'
complete -c e2undo -s h --description 'Display a usage message.'
complete -c e2undo -s n --description 'Dry-run; do not actually write blocks back to the filesystem.'
complete -c e2undo -s o --description 'Specify the filesystem\'s  offset (in bytes) fro… [See Man Page]'
complete -c e2undo -s v --description 'Report which block we\'re currently replaying.'

