# edit
# Autogenerated from man page /usr/share/man/man1/edit.1.gz
# using Deroffing man parser
complete -c edit -o ccommand --description 'Execute  command when editing begins.'
complete -c edit -s l --description 'Start in a special mode useful for the  Lisp pr… [See Man Page]'
complete -c edit -o 'r[filename]' -s L --description 'When no argument is supplied with this option, … [See Man Page]'
complete -c edit -s R --description 'Files are opened read-only when this option is given.'
complete -c edit -s s --description 'Script mode; all feedback for interactive editing is disabled.'
complete -c edit -s t --description 'Read the  tags file, then choose the file and p… [See Man Page]'
complete -c edit -s v --description 'Start in visual mode even if called as R ex .'
complete -c edit -s V --description 'Echo command input to standard error, unless it… [See Man Page]'
complete -c edit -s w --description 'Specify the size of the editing window for visual mode.'
complete -c edit -s c --description 'Execute command when editing begins.'
complete -c edit -s r --description 'When no argument is supplied with this option, … [See Man Page]'

