# efivar
# Autogenerated from man page /usr/share/man/man1/efivar.1.gz
# using Deroffing man parser
complete -c efivar -s L -l list-guids --description 'list guids efivar knows about.'
complete -c efivar -s l -l list --description 'list current variables.'
complete -c efivar -s p -l print --description 'print variable specified by --name.'
complete -c efivar -s n -l name --description 'variable to manipulate, in the form 8be4df61-93… [See Man Page]'
complete -c efivar -s a -l append --description 'append to variable specified by --name.'
complete -c efivar -s f -l fromfile --description 'use data from <file>.'
complete -c efivar -s t -l attributes --description 'attributes to use on append . SS "Help options:".'
complete -c efivar -s '?' -l help --description 'Show this help message.'
complete -c efivar -l usage --description 'Display brief usage message.'

