# era_dump
# Autogenerated from man page /usr/share/man/man8/era_dump.8.gz
# using Deroffing man parser
complete -c era_dump -s r -l 'repair.' --description 'Repair the metadata whilst dumping it.'
complete -c era_dump -s h -l 'help.' --description 'Print help and exit.'
complete -c era_dump -s V -l 'version.' --description 'Output version information and exit.'
complete -c era_dump -l 'logical.' --description 'Fold any unprocessed write sets into the final era array.'

