# era_invalidate
# Autogenerated from man page /usr/share/man/man8/era_invalidate.8.gz
# using Deroffing man parser
complete -c era_invalidate -s h -l help --description 'Print help and exit.'
complete -c era_invalidate -s V -l version --description 'Output version information and exit.'
complete -c era_invalidate -s o --description 'Write output to a file rather than stdout EXAMP… [See Man Page]'

