# ex
# Autogenerated from man page /usr/share/man/man1/ex.1p.gz
# using Deroffing man parser
complete -c ex -s 1 --description 'addr1 ,c addr2 ,c addr2 + count.'
complete -c ex -o '1)' --description '.'
complete -c ex -s i --description '(interactive mode).'
complete -c ex -s m --description '.'
complete -c ex -s e --description 'option of sed .'
complete -c ex -s x --description 'option, which did encryption based on the algor… [See Man Page]'
complete -c ex -s 2 --description 'Two lines before the current line.'

