# fsck
# Autogenerated from man page /usr/share/man/man8/fsck.reiserfs.8.gz
# using Deroffing man parser
complete -c fsck -l rebuild-sb --description 'This option recovers the superblock on a Reiserfs partition.'
complete -c fsck -l check --description 'This default action checks filesystem consisten… [See Man Page]'
complete -c fsck -l fix-fixable --description 'This option recovers certain kinds of corruptio… [See Man Page]'
complete -c fsck -l rebuild-tree --description 'This option rebuilds the entire filesystem tree… [See Man Page]'
complete -c fsck -l clean-attributes --description 'This option cleans reserved fields of Stat-Data items.'
complete -c fsck -l journal --description 'This option supplies the device name of the cur… [See Man Page]'
complete -c fsck -l interactive -s i --description '\\" This makes reiserfsck to stop after each pass completed. \\".'
complete -c fsck -l adjust-size --description 'This option causes reiserfsck to correct file s… [See Man Page]'
complete -c fsck -l badblocks --description 'This option sets the badblock list to be the li… [See Man Page]'
complete -c fsck -l logfile --description 'This option causes reiserfsck to report any cor… [See Man Page]'
complete -c fsck -l nolog --description 'This option prevents reiserfsck from reporting … [See Man Page]'
complete -c fsck -l quiet -s q --description 'This option prevents reiserfsck from reporting … [See Man Page]'
complete -c fsck -l yes --description 'This option inhibits reiserfsck from asking you… [See Man Page]'
complete -c fsck -l no-journal-available --description 'This option allows reiserfsck to proceed when t… [See Man Page]'
complete -c fsck -l scan-whole-partition -s S --description 'This option causes --rebuild-tree to scan the w… [See Man Page]'

