# fstrim
# Autogenerated from man page /usr/share/man/man8/fstrim.8.gz
# using Deroffing man parser
complete -c fstrim -s a -l all --description 'Trim all mounted filesystems on devices that su… [See Man Page]'
complete -c fstrim -s o -l offset --description 'Byte offset in the filesystem from which to beg… [See Man Page]'
complete -c fstrim -s l -l length --description 'The number of bytes (after the starting point) … [See Man Page]'
complete -c fstrim -s m -l minimum --description 'Minimum contiguous free range to discard, in bytes.'
complete -c fstrim -s v -l verbose --description 'Verbose execution.'
complete -c fstrim -s V -l version --description 'Display version information and exit.'
complete -c fstrim -s h -l help --description 'Display help text and exit.'

