# gendsa
# Autogenerated from man page /usr/share/man/man1/gendsa.1ssl.gz
# using Type1
complete -c gendsa -o aes128 -o aes192 -o aes256 -o camellia128 -o camellia192 -o camellia256 -o des -o des3 -o idea --description 'These options encrypt the private key with spec… [See Man Page]'
complete -c gendsa -o rand --description 'a file or files containing random data used to … [See Man Page]'
complete -c gendsa -o engine --description 'specifying an engine (by its unique id string) … [See Man Page]'

