# git-replace
# Autogenerated from man page /usr/share/man/man1/git-replace.1.gz
# using Deroffing man parser
complete -c git-replace -s f -l force --description 'If an existing replace ref for the same object … [See Man Page]'
complete -c git-replace -s d -l delete --description 'Delete existing replace refs for the given objects.'
complete -c git-replace -l edit --description 'Edit an object\\(cqs content interactively.'
complete -c git-replace -l raw --description 'When editing, provide the raw object contents r… [See Man Page]'
complete -c git-replace -l graft --description 'Create a graft commit.'
complete -c git-replace -s l -l list --description 'List replace refs for objects that match the gi… [See Man Page]'
complete -c git-replace -l format --description 'When listing, use the specified <format>, which… [See Man Page]'

