# git-interpret-trailers
# Autogenerated from man page /usr/share/man/man1/git-interpret-trailers.1.gz
# using Deroffing man parser
complete -c git-interpret-trailers -l in-place --description 'Edit the files in place.'
complete -c git-interpret-trailers -l trim-empty --description 'If the <value> part of any trailer contains onl… [See Man Page]'
complete -c git-interpret-trailers -l trailer --description 'Specify a (<token>, <value>) pair that should b… [See Man Page]'

