# git-commit-tree
# Autogenerated from man page /usr/share/man/man1/git-commit-tree.1.gz
# using Deroffing man parser
complete -c git-commit-tree -s p --description 'Each -p indicates the id of a parent commit object.'
complete -c git-commit-tree -s m --description 'A paragraph in the commit log message.'
complete -c git-commit-tree -s F --description 'Read the commit log message from the given file.'
complete -c git-commit-tree -o 'S[<keyid>]' -l 'gpg-sign[' --description 'GPG-sign commits.'
complete -c git-commit-tree -l no-gpg-sign --description 'Do not GPG-sign commit, to countermand a --gpg-… [See Man Page]'
complete -c git-commit-tree -l gpg-sign --description 'option given earlier on the command line.'

