# git-worktree
# Autogenerated from man page /usr/share/man/man1/git-worktree.1.gz
# using Deroffing man parser
complete -c git-worktree -s f -l force --description 'By default, add refuses to create a new working… [See Man Page]'
complete -c git-worktree -s b -s B --description 'With add, create a new branch named <new-branch… [See Man Page]'
complete -c git-worktree -l detach --description 'With add, detach HEAD in the new working tree.'
complete -c git-worktree -l '[no-]checkout' --description 'By default, add checks out <branch>, however, -… [See Man Page]'
complete -c git-worktree -s n -l dry-run --description 'With prune, do not remove anything; just report… [See Man Page]'
complete -c git-worktree -l porcelain --description 'With list, output in an easy-to-parse format for scripts.'
complete -c git-worktree -s v -l verbose --description 'With prune, report all removals.'
complete -c git-worktree -l expire --description 'With prune, only expire unused working trees older than <time>.'
complete -c git-worktree -l reason --description 'With lock, an explanation why the working tree is locked.'
complete -c git-worktree -l detached --description 'used, then, as a convenience, a new branch base… [See Man Page]'
complete -c git-worktree -l 'reason.' --description 'prune.'
complete -c git-worktree -l no-checkout --description 'can be used to suppress checkout in order to ma… [See Man Page]'

