# gpg-error-config
# Autogenerated from man page /usr/share/man/man1/gpg-error-config.1.gz
# using Deroffing man parser
complete -c gpg-error-config -l mt --description 'Provide output appropriate for multithreaded programs.'
complete -c gpg-error-config -l version --description 'Print the currently installed version of Libgpg… [See Man Page]'
complete -c gpg-error-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c gpg-error-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c gpg-error-config -l prefix --description 'If specified, use prefix instead of the install… [See Man Page]'
complete -c gpg-error-config -l exec-prefix --description 'If specified, use prefix instead of the install… [See Man Page]'

