# groupmod
# Autogenerated from man page /usr/share/man/man8/groupmod.8.gz
# using Deroffing man parser
complete -c groupmod -s g -l gidGID --description 'The group ID of the given GROUP will be changed to GID.'
complete -c groupmod -s h -l help --description 'Display help message and exit.'
complete -c groupmod -s n -l new-nameNEW_GROUP --description 'The name of the group will be changed from GROU… [See Man Page]'
complete -c groupmod -s o -l non-unique --description 'When used with the -g option, allow to change t… [See Man Page]'
complete -c groupmod -s p -l passwordPASSWORD --description 'The encrypted password, as returned by crypt(3).'
complete -c groupmod -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c groupmod -l gid --description '.'
complete -c groupmod -l new-name --description '.'
complete -c groupmod -l password --description '.'
complete -c groupmod -l root --description '.'

