# groupdel
# Autogenerated from man page /usr/share/man/man8/groupdel.8.gz
# using Deroffing man parser
complete -c groupdel -s h -l help --description 'Display help message and exit.'
complete -c groupdel -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c groupdel -l root --description '.'

