# groupadd
# Autogenerated from man page /usr/share/man/man8/groupadd.8.gz
# using Deroffing man parser
complete -c groupadd -s f -l force --description 'This option causes the command to simply exit w… [See Man Page]'
complete -c groupadd -s g -l gidGID --description 'The numerical value of the group\\*(Aqs ID.'
complete -c groupadd -s h -l help --description 'Display help message and exit.'
complete -c groupadd -s K -l keyKEY --description 'Overrides /etc/login.'
complete -c groupadd -s o -l non-unique --description 'This option permits to add a group with a non-unique GID.'
complete -c groupadd -s p -l passwordPASSWORD --description 'The encrypted password, as returned by crypt(3).'
complete -c groupadd -s r -l system --description 'Create a system group.'
complete -c groupadd -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c groupadd -l gid --description '.'
complete -c groupadd -l key --description '.'
complete -c groupadd -l password --description '.'
complete -c groupadd -l root --description '.'

