# groupmems
# Autogenerated from man page /usr/share/man/man8/groupmems.8.gz
# using Deroffing man parser
complete -c groupmems -s a -l adduser_name --description 'Add an user to the group membership list.'
complete -c groupmems -s d -l deleteuser_name --description 'Delete a user from the group membership list.'
complete -c groupmems -s g -l groupgroup_name --description 'The superuser can specify which group membershi… [See Man Page]'
complete -c groupmems -s h -l help --description 'Display help message and exit.'
complete -c groupmems -s l -l list --description 'List the group membership list.'
complete -c groupmems -s p -l purge --description 'Purge all users from the group membership list.'
complete -c groupmems -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c groupmems -l add --description '.'
complete -c groupmems -l delete --description '.'
complete -c groupmems -l group --description '.'
complete -c groupmems -l root --description '.'

