# ibus
# Autogenerated from man page /usr/share/man/man1/ibus.1.gz
# using Deroffing man parser
complete -c ibus -l system --description 'is not given.'
complete -c ibus -l file --description 'is given.'

