# ids2ngram
# Autogenerated from man page /usr/share/man/man1/ids2ngram.1.gz
# using Type1
complete -c ids2ngram -s n -l NMax --description 'Generates N-gram result.'
complete -c ids2ngram -s s -l swap --description 'Specify the temporary intermediate file.'
complete -c ids2ngram -s o -l out --description 'Specify the result idngram file, e. g.  the array of [id1, .'

