# ijsgutenprint
# Autogenerated from man page /usr/share/man/man1/ijsgutenprint.1.gz
# using Deroffing man parser
complete -c ijsgutenprint -o dIjsUseOutputFD --description 'This option should be specified whenever output… [See Man Page]'
complete -c ijsgutenprint -o sIjsParams --description 'This parameter contains a single string contain… [See Man Page]'
complete -c ijsgutenprint -o sDeviceManufacturer -o sDeviceModel --description 'This option must be supplied.   There is no default.'

