# ip-link
# Autogenerated from man page /usr/share/man/man8/ip-link.8.gz
# using Deroffing man parser
complete -c ip-link -s t -s A -s j -l set-class --description 'and this "4" priority can be used in the egress… [See Man Page]'

