# ip-netns
# Autogenerated from man page /usr/share/man/man8/ip-netns.8.gz
# using Deroffing man parser
complete -c ip-netns -o all --description 'option was specified then all the network names… [See Man Page]'

