# ldconfig
# Autogenerated from man page /usr/share/man/man8/ldconfig.8.gz
# using Deroffing man parser
complete -c ldconfig -s c -l format --description '(Since glibc 2.'
complete -c ldconfig -s C --description 'Use  cache instead of R /etc/ld. so. cache .'
complete -c ldconfig -s f --description 'Use  conf instead of R /etc/ld. so. conf . \\" FIXME glibc 2.'
complete -c ldconfig -s i -l ignore-aux-cache --description '(Since glibc 2. 7) .'
complete -c ldconfig -s l --description '(Since glibc 2. 2) Library mode.'
complete -c ldconfig -s n --description 'Only process directories specified on the command line.'
complete -c ldconfig -s N --description 'Don\'t rebuild the cache.'
complete -c ldconfig -s p -l print-cache --description 'Print the lists of directories and candidate li… [See Man Page]'
complete -c ldconfig -s r --description 'Change to and use  root as the root directory.'
complete -c ldconfig -s v -l verbose --description 'Verbose mode.'
complete -c ldconfig -s V -l version --description 'Print program version.'
complete -c ldconfig -s X --description 'is also specified, links are still updated.'

