# libinput-list-devices
# Autogenerated from man page /usr/share/man/man1/libinput-list-devices.1.gz
# using Deroffing man parser
complete -c libinput-list-devices -l help --description 'Print help NOTES.'

