# libinput-debug-events
# Autogenerated from man page /usr/share/man/man1/libinput-debug-events.1.gz
# using Deroffing man parser
complete -c libinput-debug-events -l help --description 'Print help.'

