# lou_checktable
# Autogenerated from man page /usr/share/man/man1/lou_checktable.1.gz
# using Deroffing man parser
complete -c lou_checktable -s h -l help --description 'display this help and exit.'
complete -c lou_checktable -s v -l version --description 'display version information and exit.'
complete -c lou_checktable -s q -l quiet --description 'do not write to standard error if there are no errors.'

