# lou_translate
# Autogenerated from man page /usr/share/man/man1/lou_translate.1.gz
# using Deroffing man parser
complete -c lou_translate -s h -l help --description 'display this help and exit.'
complete -c lou_translate -s v -l version --description 'display version information and exit.'
complete -c lou_translate -s f -l forward --description 'forward translation using the given table.'
complete -c lou_translate -s b -l backward --description 'backward translation using the given table If n… [See Man Page]'

