# lou_checkhyphens
# Autogenerated from man page /usr/share/man/man1/lou_checkhyphens.1.gz
# using Deroffing man parser
complete -c lou_checkhyphens -s h -l help --description 'display this help and exit.'
complete -c lou_checkhyphens -s v -l version --description 'display version information and exit AUTHOR Written by John J.'

