# lou_checkyaml
# Autogenerated from man page /usr/share/man/man1/lou_checkyaml.1.gz
# using Deroffing man parser
complete -c lou_checkyaml -s h -l help --description 'display this help and exit.'
complete -c lou_checkyaml -s v -l version --description 'display version information and exit AUTHOR Wri… [See Man Page]'

