# lou_debug
# Autogenerated from man page /usr/share/man/man1/lou_debug.1.gz
# using Deroffing man parser
complete -c lou_debug -s h -l help --description 'display this help and exit.'
complete -c lou_debug -s v -l version --description 'display version information and exit AUTHOR Written by John J.'

