# lou_trace
# Autogenerated from man page /usr/share/man/man1/lou_trace.1.gz
# using Deroffing man parser
complete -c lou_trace -s h -l help --description 'display this help and exit.'
complete -c lou_trace -s v -l version --description 'display version information and exit.'
complete -c lou_trace -s f -l forward --description 'forward translation using the given table.'
complete -c lou_trace -s b -l backward --description 'backward translation using the given table If n… [See Man Page]'

