# lvm-lvpoll
# Autogenerated from man page /usr/share/man/man8/lvm-lvpoll.8.gz
# using Deroffing man parser
complete -c lvm-lvpoll -l polloperation --description 'Mandatory option.'
complete -c lvm-lvpoll -l abort --description 'Abort pvmove in progress.   See pvmove(8).'
complete -c lvm-lvpoll -l handlemissingpvs --description 'Used when the polling operation needs to handle… [See Man Page]'
complete -c lvm-lvpoll -s i -l interval --description 'Report progress at regular intervals.'

