# lvmconf
# Autogenerated from man page /usr/share/man/man8/lvmconf.8.gz
# using Deroffing man parser
complete -c lvmconf -l disable-cluster --description 'Set locking_type to the default non-clustered type.'
complete -c lvmconf -l enable-cluster --description 'Set locking_type to the default clustered type on this system.'
complete -c lvmconf -l disable-halvm --description 'Set locking_type to the default non-clustered type.'
complete -c lvmconf -l enable-halvm --description 'Set locking_type suitable for HA LVM use.'
complete -c lvmconf -l file --description 'Apply the changes to configfile instead of the … [See Man Page]'
complete -c lvmconf -l lockinglib --description 'Set external locking_library locking library to… [See Man Page]'
complete -c lvmconf -l lockinglibdir --description '.'
complete -c lvmconf -l services --description 'In addition to setting the lvm configuration, a… [See Man Page]'
complete -c lvmconf -l mirrorservice --description 'Also enable or disable optional cmirrord servic… [See Man Page]'
complete -c lvmconf -l startstopservices --description 'In addition to enabling or disabling related se… [See Man Page]'

