# lvscan
# Autogenerated from man page /usr/share/man/man8/lvscan.8.gz
# using Deroffing man parser
complete -c lvscan -l all --description 'Include information in the output about interna… [See Man Page]'
complete -c lvscan -s b -l blockdevice --description 'This option is now ignored.'
complete -c lvscan -l cache --description 'Applicable only when lvmetad(8) is in use (see also lvm.'
complete -c lvscan -l 'monitor).' --description 'SEE ALSO lvm (8), lvcreate (8), lvdisplay (8) lvs (8).'

