# mknod
# Autogenerated from man page /usr/share/man/man1/mknod.1.gz
# using Deroffing man parser
complete -c mknod -s m -l mode --description 'set file permission bits to MODE, not a=rw - umask.'
complete -c mknod -s Z --description 'set the SELinux security context to default type.'
complete -c mknod -l 'context[' --description 'like -Z, or if CTX is specified then set the SE… [See Man Page]'
complete -c mknod -l help --description 'display this help and exit.'
complete -c mknod -l version --description 'output version information and exit .'

