# mmroff
# Autogenerated from man page /usr/share/man/man1/mmroff.1.gz
# using Deroffing man parser
complete -c mmroff -s z --description 'and.'
complete -c mmroff -o rRef --description 'to collect all cross references and then to do … [See Man Page]'
complete -c mmroff -s x --description 'Just create the cross reference file.'

