# mmseg
# Autogenerated from man page /usr/share/man/man1/mmseg.1.gz
# using Type1
complete -c mmseg -s d --description 'Use dict_file as lexicon.'
complete -c mmseg -s f -l format --description 'Output Format, can be \'text\' or \'bin\'.  default \'bin\'.'
complete -c mmseg -s s -l stok --description 'Sentence token id.  Default 10.'
complete -c mmseg -s i -l show-id --description 'Show Id info.'

