# mountpoint
# Autogenerated from man page /usr/share/man/man1/mountpoint.1.gz
# using Deroffing man parser
complete -c mountpoint -s d -l fs-devno --description 'Show the major/minor numbers of the device that… [See Man Page]'
complete -c mountpoint -s q -l quiet --description 'Be quiet - don\'t print anything.'
complete -c mountpoint -s x -l devno --description 'Show the major/minor numbers of the given block… [See Man Page]'
complete -c mountpoint -s V -l version --description 'Display version information and exit.'
complete -c mountpoint -s h -l help --description 'Display help text and exit.'

