# mupdf
# Autogenerated from man page /usr/share/man/man1/mupdf.1.gz
# using Deroffing man parser
complete -c mupdf -s p --description 'Uses the given password to open an encrypted PDF file.'
complete -c mupdf -s r --description 'Changes the initial zoom level, specified as th… [See Man Page]'
complete -c mupdf -s A --description 'Changes the anti-aliasing quality, specified as… [See Man Page]'
complete -c mupdf -s C --description 'Sets the full-page tint using hexadecimal color syntax.'
complete -c mupdf -s W --description 'Page width in points for EPUB layout.'
complete -c mupdf -s H --description 'Page height in points for EPUB layout.'
complete -c mupdf -s S --description 'Font size in points for EPUB layout.'
complete -c mupdf -s U --description 'User style sheet for EPUB layout.'

