# ncdump
# Autogenerated from man page /usr/share/man/man1/ncdump.1.gz
# using Deroffing man parser
complete -c ncdump -s c --description 'Show the values of coordinate variables (1D var… [See Man Page]'
complete -c ncdump -s h --description 'Show only the header information in the output,… [See Man Page]'
complete -c ncdump -s v --description 'The output will include data values for the spe… [See Man Page]'
complete -c ncdump -s b --description 'A brief annotation in the form of a CDL comment… [See Man Page]'
complete -c ncdump -s f --description 'Full annotations in the form of trailing CDL co… [See Man Page]'
complete -c ncdump -s l --description 'Changes the default maximum line length (80) us… [See Man Page]'
complete -c ncdump -s n --description 'CDL requires a name for a netCDF file, for use … [See Man Page]'
complete -c ncdump -s p --description 'Specifies default precision (number of signific… [See Man Page]'
complete -c ncdump -s k --description 'Show kind of netCDF file the pathname reference… [See Man Page]'
complete -c ncdump -s s --description 'Output special virtual attributes that provide … [See Man Page]'
complete -c ncdump -s t --description 'Controls display of time data, if stored in a v… [See Man Page]'
complete -c ncdump -s i --description 'Same as the \'-t\' option, except output time dat… [See Man Page]'
complete -c ncdump -s g --description 'For netCDF-4 files, the output will include dat… [See Man Page]'
complete -c ncdump -s w --description 'For file names that request remote access using… [See Man Page]'
complete -c ncdump -s x --description 'Output XML (NcML) instead of CDL.'

