# ncgen
# Autogenerated from man page /usr/share/man/man1/ncgen.1.gz
# using Deroffing man parser
complete -c ncgen -s b --description 'Create a (binary) netCDF file.'
complete -c ncgen -s c --description 'Generate  C source code that will create a netC… [See Man Page]'
complete -c ncgen -s f --description 'Generate  FORTRAN 77 source code that will crea… [See Man Page]'
complete -c ncgen -s o --description 'Name of the file to pass to calls to "nc_create()".'
complete -c ncgen -o format_code --description 'The -k flag specifies the format of the file to… [See Man Page]'
complete -c ncgen -s x --description 'Don\'t initialize data with fill values.'
complete -c ncgen -s l --description 'The -l flag specifies the output language to us… [See Man Page]'
complete -c ncgen -s k --description '.'
complete -c ncgen -o '2s	//' -s 2 --description '0123s	// octal 0x7ffs  //hexadecimal int intege… [See Man Page]'
complete -c ncgen -o '2ll	//' --description '0123LL	// octal 0x7ffLL  //hexadecimal Floating… [See Man Page]'
complete -c ncgen -o '2.0f' --description '3. 14159265358979f	// will be truncated to less precision 1.'
complete -c ncgen -o '2.0' --description '3. 141592653589793 1. 0e-20 1.'

