# ncgen3
# Autogenerated from man page /usr/share/man/man1/ncgen3.1.gz
# using Deroffing man parser
complete -c ncgen3 -s b --description 'Create a (binary) netCDF file.'
complete -c ncgen3 -s c --description 'Generate  C source code that will create a netC… [See Man Page]'
complete -c ncgen3 -s f --description 'Generate  Fortran source code that will create … [See Man Page]'
complete -c ncgen3 -s o --description 'Name for the binary netCDF file created.'
complete -c ncgen3 -s k --description 'Using -k2 or -k "64-bit offset" specifies that … [See Man Page]'
complete -c ncgen3 -s x --description 'Don\'t initialize data with fill values.'
complete -c ncgen3 -o '2s	//' -s 2 --description '0123s	// octal 0x7ffs  //hexadecimal Long integ… [See Man Page]'
complete -c ncgen3 -o '2.0f' --description '3. 14159265358979f	// will be truncated to less precision 1.'
complete -c ncgen3 -o '2.0' --description '3. 141592653589793 1. 0e-20 1. d.'

