# NetworkManager
# Autogenerated from man page /usr/share/man/man8/NetworkManager.8.gz
# using Deroffing man parser
complete -c NetworkManager -l version -s V --description 'Print the NetworkManager software version and exit.'
complete -c NetworkManager -l help -s h --description 'Print NetworkManager\\*(Aqs available options and exit.'
complete -c NetworkManager -l no-daemon -s n --description 'Do not daemonize.'
complete -c NetworkManager -l debug -s d --description 'Do not daemonize, and direct log output to the … [See Man Page]'
complete -c NetworkManager -l pid-file -s p --description 'Specify location of a PID file.'
complete -c NetworkManager -l state-file --description 'Specify file for storing state of the NetworkMa… [See Man Page]'
complete -c NetworkManager -l config --description 'Specify configuration file to set up various se… [See Man Page]'
complete -c NetworkManager -l plugins --description 'List plugins used to manage system-wide connection settings.'
complete -c NetworkManager -l log-level --description 'Sets how much information NetworkManager sends … [See Man Page]'
complete -c NetworkManager -l log-domains --description 'A comma-separated list specifying which operati… [See Man Page]'
complete -c NetworkManager -l print-config --description 'Print the NetworkManager configuration to stdout and exit.'

