# nm-online
# Autogenerated from man page /usr/share/man/man1/nm-online.1.gz
# using Deroffing man parser
complete -c nm-online -s t -l timeout --description 'Time to wait for a connection, in seconds.'
complete -c nm-online -s x -l exit --description 'Exit immediately if NetworkManager is not runni… [See Man Page]'
complete -c nm-online -s q -l quiet --description 'Don\\*(Aqt print anything.'
complete -c nm-online -s s -l wait-for-startup --description 'Wait for NetworkManager startup to complete, ra… [See Man Page]'

