# nmcli
# Autogenerated from man page /usr/share/man/man1/nmcli.1.gz
# using Deroffing man parser
complete -c nmcli -s t -l terse --description 'Output is terse.'
complete -c nmcli -s p -l pretty --description 'Output is pretty.'
complete -c nmcli -s c -l colors --description 'This option controls color output (using termin… [See Man Page]'
complete -c nmcli -s f -l fields --description 'This option is used to specify what fields (col… [See Man Page]'
complete -c nmcli -s e -l escape --description 'Whether to escape : and  characters in terse tabular mode.'
complete -c nmcli -s a -l ask --description 'When using this option nmcli will stop and ask … [See Man Page]'
complete -c nmcli -s s -l show-secrets --description 'When using this option nmcli will display passw… [See Man Page]'
complete -c nmcli -s w -l wait --description 'This option sets a timeout period for which nmc… [See Man Page]'
complete -c nmcli -l complete-args --description 'Instead of conducting the desired action, nmcli… [See Man Page]'
complete -c nmcli -s v -l version --description 'Show nmcli version.'
complete -c nmcli -s h -l help --description 'Print help information.'
complete -c nmcli -s m -l mode --description '.'
complete -c nmcli -l active --description 'option is specified, only the active profiles are shown.'
complete -c nmcli -l order --description 'option can be used to get custom ordering of connections.'
complete -c nmcli -o 'a:na).' --description 'show [--active] [id | uuid | path | apath] ID.'
complete -c nmcli -l 'ask.' --description '.'
complete -c nmcli -l temporary --description 'option is specified, in which case the new prof… [See Man Page]'
complete -c nmcli -l 'ask).' --description 'nmcli handle all polkit requests, not only Netw… [See Man Page]'

