# nss-config
# Autogenerated from man page /usr/share/man/man1/nss-config.1.gz
# using Deroffing man parser
complete -c nss-config -l prefix --description 'Returns the top level system directory under wh… [See Man Page]'
complete -c nss-config -l exec-prefix --description 'returns the top level system directory under wh… [See Man Page]'
complete -c nss-config -l includedir --description 'returns the path to the directory were the nss … [See Man Page]'
complete -c nss-config -l version --description 'returns the upstream version of nss in the form… [See Man Page]'
complete -c nss-config -l libs --description 'returns the compiler linking flags.'
complete -c nss-config -l cflags --description 'returns the compiler include flags.'
complete -c nss-config -l libdir --description 'returns the path to the directory were the nss … [See Man Page]'

