# ntfsrecover
# Autogenerated from man page /usr/share/man/man8/ntfsrecover.8.gz
# using Deroffing man parser
complete -c ntfsrecover -s b -l backward --description 'Examine the actions described in the logfile ba… [See Man Page]'
complete -c ntfsrecover -s c -l clusters --description 'Restrict the output generated when using option… [See Man Page]'
complete -c ntfsrecover -s f -l forward --description 'Examine the actions described in the logfile fo… [See Man Page]'
complete -c ntfsrecover -s h -l help --description 'Show some help information.'
complete -c ntfsrecover -s n -l no-action --description 'Do not apply any modification, useful when usin… [See Man Page]'
complete -c ntfsrecover -s p -l play --description 'Undo COUNT transaction sets and redo a single o… [See Man Page]'
complete -c ntfsrecover -s r -l range --description 'Examine the actions described in the logfile fo… [See Man Page]'
complete -c ntfsrecover -s s -l sync --description 'Sync the file system by applying the committed … [See Man Page]'
complete -c ntfsrecover -s t -l transactions --description 'Display the transaction parameters when examini… [See Man Page]'
complete -c ntfsrecover -s u -l undo --description 'Undo COUNT transaction sets, thus resetting the… [See Man Page]'
complete -c ntfsrecover -s v -l verbose --description 'Display more debug/warning/error messages.'
complete -c ntfsrecover -o bv --description 'is equivalent to.'
complete -c ntfsrecover -s V -l version --description 'Show the version number, copyright and license of ntfsrecover .'

