# ntfsdecrypt
# Autogenerated from man page /usr/share/man/man8/ntfsdecrypt.8.gz
# using Deroffing man parser
complete -c ntfsdecrypt -s i -l inode --description 'Display or update the contents of a file design… [See Man Page]'
complete -c ntfsdecrypt -s e -l encrypt --description 'Update an existing encrypted file and get the n… [See Man Page]'
complete -c ntfsdecrypt -s f -l force --description 'This will override some sensible defaults, such… [See Man Page]'
complete -c ntfsdecrypt -s k -l keyfile-name --description 'Define the file which contains the public and p… [See Man Page]'
complete -c ntfsdecrypt -s h -l help --description 'Show a list of options with a brief description of each one.'
complete -c ntfsdecrypt -s q -l quiet --description 'Suppress some debug/warning/error messages.'
complete -c ntfsdecrypt -s V -l version --description 'Show the version number, copyright and license … [See Man Page]'
complete -c ntfsdecrypt -o fv --description 'is equivalent to.'
complete -c ntfsdecrypt -s v --description 'Long named options can be abbreviated to any un… [See Man Page]'
complete -c ntfsdecrypt -l verbose --description 'Display more debug/warning/error messages.'

