# ntfswipe
# Autogenerated from man page /usr/share/man/man8/ntfswipe.8.gz
# using Deroffing man parser
complete -c ntfswipe -s a -l all --description 'Wipe all unused space.  This may take significant time.'
complete -c ntfswipe -s b -l bytes --description 'Define the allowed replacement bytes which are … [See Man Page]'
complete -c ntfswipe -s c -l count --description 'Define the number of times the unused space is … [See Man Page]'
complete -c ntfswipe -s d -l directory --description 'Wipe all the directory indexes, which may conta… [See Man Page]'
complete -c ntfswipe -s f -l force --description 'This will override some sensible defaults, such… [See Man Page]'
complete -c ntfswipe -s h -l help --description 'Show a list of options with a brief description of each one.'
complete -c ntfswipe -s i -l info --description 'Display details about unused space, without wiping anything.'
complete -c ntfswipe -s l -l logfile --description 'Overwrite the logfile (update journal).'
complete -c ntfswipe -s m -l mft --description 'Overwrite the unused space in the MFT (main fil… [See Man Page]'
complete -c ntfswipe -s n -l no-action --description 'Executes the wiping process without writing to device.'
complete -c ntfswipe -s p -l pagefile --description 'Overwrite the Windows swap space.'
complete -c ntfswipe -s q -l quiet --description 'Suppress some debug/warning/error messages.'
complete -c ntfswipe -s s -l undel --description 'Overwrite the space which had been allocated to… [See Man Page]'
complete -c ntfswipe -s t -l tails --description 'Overwrite the space at the end of files which i… [See Man Page]'
complete -c ntfswipe -s u -l unused --description 'Overwrite the space which is currently not allo… [See Man Page]'
complete -c ntfswipe -s U -l unused-fast --description 'Overwrite the space which is currently not allo… [See Man Page]'
complete -c ntfswipe -s v -l verbose --description 'Display more debug/warning/error messages.'
complete -c ntfswipe -o fv --description 'is equivalent to.'
complete -c ntfswipe -o 'U)' --description '.'
complete -c ntfswipe -s V -l version --description 'Show the version number, copyright and license of ntfswipe .'

