# ntfs-3g
# Autogenerated from man page /usr/share/man/man8/ntfs-3g.secaudit.8.gz
# using Deroffing man parser
complete -c ntfs-3g -o 'a[rv]' --description 'Audits the volume : all the global security dat… [See Man Page]'
complete -c ntfs-3g -o 'r[v]' --description 'displays the security parameters of all files a… [See Man Page]'
complete -c ntfs-3g -o 'b[v]' --description 'Recursively extracts to standard output the NTF… [See Man Page]'
complete -c ntfs-3g -o 's[ev]' --description 'Sets the NTFS ACLS as indicated in backup-file … [See Man Page]'
complete -c ntfs-3g -o 'u[v]' --description 'Displays a proposed contents for a user mapping… [See Man Page]'

