# nyancat
# Autogenerated from man page /usr/share/man/man1/nyancat.1.gz
# using Deroffing man parser
complete -c nyancat -s i -l intro --description 'Show introduction / about information on startup.'
complete -c nyancat -s I -l skip-intro --description 'Skip the introduction in telnet mode.'
complete -c nyancat -s t -l telnet --description 'Enable telnet mode.'
complete -c nyancat -s n -l no-counter --description 'Do not display the timer.'
complete -c nyancat -s s -l no-title --description 'Do not set the titlebar text.'
complete -c nyancat -s e -l no-clear --description 'Do not clear the display between frames.'
complete -c nyancat -s f -l frames --description 'Display the requested number of frames, then quit.'
complete -c nyancat -s r -l min-rows --description 'Crop the animation from the top.'
complete -c nyancat -s R -l max-rows --description 'Crop the animation from the bottom.'
complete -c nyancat -s c -l min-cols --description 'Crop the animation from the left.'
complete -c nyancat -s C -l max-cols --description 'Crop the animation from the right.'
complete -c nyancat -s W -l width --description 'Crop the animation to the given width.'
complete -c nyancat -s H -l height --description 'Crop the animation to the given height.'
complete -c nyancat -s h -l help --description 'Show help message and exit.  HOMEPAGE.'

