# ocsptool
# Autogenerated from man page /usr/share/man/man1/ocsptool.1.gz
# using Type1
complete -c ocsptool -o 'no-nonce\\f[]' --description 'Use (or not) a nonce to OCSP request.'
complete -c ocsptool -o 'no-inder\\f[]' --description 'Use DER format for input certificates and private keys.'

