# omxregister-bellagio
# Autogenerated from man page /usr/share/man/man1/omxregister-bellagio.1.gz
# using Deroffing man parser
complete -c omxregister-bellagio -s v --description 'Display a verbose output, listing all the compo… [See Man Page]'
complete -c omxregister-bellagio -s h --description 'Display help.'

