# opj_decompress
# Autogenerated from man page /usr/share/man/man1/opj_decompress.1.gz
# using Deroffing man parser
complete -c opj_decompress -s i --description '(jpeg2000 input file name).'
complete -c opj_decompress -s l --description 'n is the maximum number of quality layers to decode.'
complete -c opj_decompress -s o --description '(output file name with extension).'
complete -c opj_decompress -s r --description '(n is the highest resolution level to be discarded.'
complete -c opj_decompress -s x --description '(use name as index file and fill it).'
complete -c opj_decompress -o ImgDir --description '(directory containing input files).'
complete -c opj_decompress -o OutFor --description '(extension for output files).'
complete -c opj_decompress -o jpip --description 'Embed index table box into the output JP2 file … [See Man Page]'
complete -c opj_decompress -o TP --description 'Partition a tile into tile parts of different r… [See Man Page]'
complete -c opj_decompress -s W --description '.'

