# p11-kit
# Autogenerated from man page /usr/share/man/man8/p11-kit.8.gz
# using Deroffing man parser
complete -c p11-kit -s v -l verbose --description '.'
complete -c p11-kit -s q -l quiet --description '.'

