# partx
# Autogenerated from man page /usr/share/man/man8/partx.8.gz
# using Deroffing man parser
complete -c partx -s a -l add --description 'Add the specified partitions, or read the disk … [See Man Page]'
complete -c partx -s b -l bytes --description 'Print the SIZE column in bytes rather than in h… [See Man Page]'
complete -c partx -s d -l delete --description 'Delete the specified partitions or all partitions.'
complete -c partx -s g -l noheadings --description 'Do not print a header line with --show or --raw.'
complete -c partx -s l -l list --description 'List the partitions.'
complete -c partx -s n -l nr --description 'Specify the range of partitions.'
complete -c partx -s o -l output --description 'Define the output columns to use for  --show , … [See Man Page]'
complete -c partx -s P -l pairs --description 'List the partitions using the KEY="value" format.'
complete -c partx -s r -l raw --description 'List the partitions using the raw output format.'
complete -c partx -s s -l show --description 'List the partitions.'
complete -c partx -s t -l type --description 'Specify the partition table type, which can be … [See Man Page]'
complete -c partx -s u -l update --description 'Update the specified partitions.'
complete -c partx -s v -l verbose --description 'Verbose mode.'
complete -c partx -s V -l version --description 'Display version information and exit.'
complete -c partx -o 1:-1 --description 'means the last partition, and.'
complete -c partx -o 2:-1 --description 'means the last two partitions.'
complete -c partx -l help --description 'to get list of all supported columns.'
complete -c partx -s h --description 'Display help text and exit.  EXAMPLES.'

