# patchelf
# Autogenerated from man page /usr/share/man/man1/patchelf.1.gz
# using Deroffing man parser
complete -c patchelf -l page-size --description 'Uses the given page size instead of the default.'
complete -c patchelf -l set-interpreter --description 'Change the dynamic loader ("ELF interpreter") o… [See Man Page]'
complete -c patchelf -l print-interpreter --description 'Prints the ELF interpreter of the executable.'
complete -c patchelf -l print-soname --description 'Prints DT_SONAME entry of . dynamic section.'
complete -c patchelf -l set-soname --description 'Sets DT_SONAME entry of a library to SONAME.'
complete -c patchelf -l set-rpath --description 'Change the RPATH of the executable or library to RPATH.'
complete -c patchelf -l remove-rpath --description 'Removes the DT_RPATH or DT_RUNPATH entry of the… [See Man Page]'
complete -c patchelf -l shrink-rpath --description 'Remove from the RPATH all directories that do n… [See Man Page]'
complete -c patchelf -l print-rpath --description 'Prints the RPATH for an executable or library.'
complete -c patchelf -l force-rpath --description 'Forces the use of the obsolete DT_RPATH in the … [See Man Page]'
complete -c patchelf -l add-needed --description 'Adds a declared dependency on a dynamic library (DT_NEEDED).'
complete -c patchelf -l replace-needed --description 'Replaces a declared dependency on a dynamic lib… [See Man Page]'
complete -c patchelf -l remove-needed --description 'Removes a declared depency on LIBRARY (DT_NEEDED entry).'
complete -c patchelf -l no-default-lib --description 'Marks the object that the search for dependenci… [See Man Page]'
complete -c patchelf -l debug --description 'Prints details of the changes made to the input file.'
complete -c patchelf -l version --description 'Shows the version of patchelf.'

