# pdfinfo
# Autogenerated from man page /usr/share/man/man1/pdfinfo.1.gz
# using Deroffing man parser
complete -c pdfinfo -s f --description 'Specifies the first page to examine.'
complete -c pdfinfo -s l --description 'Specifies the last page to examine.'
complete -c pdfinfo -o box --description 'Prints the page box bounding boxes: MediaBox, C… [See Man Page]'
complete -c pdfinfo -o meta --description 'Prints document-level metadata.'
complete -c pdfinfo -o js --description 'Prints all JavaScript in the PDF.'
complete -c pdfinfo -o struct --description 'Prints the logical document structure of a Tagged-PDF file.'
complete -c pdfinfo -o struct-text --description 'Print the textual content along with the docume… [See Man Page]'
complete -c pdfinfo -o isodates --description 'Prints dates in ISO-8601 format (including the time zone).'
complete -c pdfinfo -o rawdates --description 'Prints the raw (undecoded) date strings, direct… [See Man Page]'
complete -c pdfinfo -o enc --description 'Sets the encoding to use for text output.'
complete -c pdfinfo -o listenc --description 'Lits the available encodings.'
complete -c pdfinfo -o opw --description 'Specify the owner password for the PDF file.'
complete -c pdfinfo -o upw --description 'Specify the user password for the PDF file.'
complete -c pdfinfo -s v --description 'Print copyright and version information.'
complete -c pdfinfo -s h --description 'Print usage information.  ( -help and.'
complete -c pdfinfo -l help --description 'are equivalent.'

