# pp
# Autogenerated from man page /usr/share/man/man1/pp.1.gz
# using Deroffing man parser
complete -c pp -s t --description 'specify the input, one of {private-key | public… [See Man Page]'
complete -c pp -s a --description 'Input is in ascii encoded form (RFC1113).'
complete -c pp -s i --description 'Define an input file to use (default is stdin).'
complete -c pp -s o --description 'Define an output file to use (default is stdout).'
complete -c pp -s u --description 'Use UTF-8 (default is to show non-ascii as . ).'
complete -c pp -s w --description 'Don\\*(Aqt wrap long output lines.'

