# pvs
# Autogenerated from man page /usr/share/man/man8/pvs.8.gz
# using Deroffing man parser
complete -c pvs -l all --description 'Include information in the output about devices… [See Man Page]'
complete -c pvs -l aligned --description 'Use with --separator to align the output columns.'
complete -c pvs -l binary --description 'Use binary values "0" or "1" instead of descrip… [See Man Page]'
complete -c pvs -l configreport --description 'Make any subsequent -o, --options, -O, --sort o… [See Man Page]'
complete -c pvs -l logonly --description 'Suppress the pvs report itself and display only… [See Man Page]'
complete -c pvs -l nameprefixes --description 'Add an "LVM2_" prefix plus the field name to the output.'
complete -c pvs -l noheadings --description 'Suppress the headings line that is normally the… [See Man Page]'
complete -c pvs -l nosuffix --description 'Suppress the suffix on output sizes.'
complete -c pvs -s o -l options --description 'Comma-separated ordered list of columns.'
complete -c pvs -l segments --description '"pv_" prefixes are optional.'
complete -c pvs -s S -l select --description 'Display only rows that match Selection criteria.'
complete -c pvs -s O -l sort --description 'Comma-separated ordered list of columns to sort by.'
complete -c pvs -l rows --description 'Output columns as rows.'
complete -c pvs -l separator --description 'String to use to separate each column.'
complete -c pvs -l unbuffered --description 'Produce output immediately without sorting or a… [See Man Page]'
complete -c pvs -l units --description 'All sizes are output in these units: (h)uman-re… [See Man Page]'
complete -c pvs -l unquoted --description 'When used with --nameprefixes, output values in… [See Man Page]'

