# renice
# Autogenerated from man page /usr/share/man/man1/renice.1.gz
# using Deroffing man parser
complete -c renice -s n -l priority --description 'Specify the scheduling  priority to be used for… [See Man Page]'
complete -c renice -s g -l pgrp --description 'Interpret the succeeding arguments as process group IDs.'
complete -c renice -s p -l pid --description 'Interpret the succeeding arguments as process I… [See Man Page]'
complete -c renice -s u -l user --description 'Interpret the succeeding arguments as usernames or UIDs.'
complete -c renice -s V -l version --description 'Display version information and exit.'
complete -c renice -s h -l help --description 'Display help text and exit.'

