# resize2fs
# Autogenerated from man page /usr/share/man/man8/resize2fs.8.gz
# using Deroffing man parser
complete -c resize2fs -s b --description 'Turns on the 64bit feature, resizes the group d… [See Man Page]'
complete -c resize2fs -s d --description 'Turns on various resize2fs debugging features, … [See Man Page]'
complete -c resize2fs -s f --description 'Forces resize2fs to proceed with the filesystem… [See Man Page]'
complete -c resize2fs -s F --description 'Flush the filesystem device\'s buffer caches before beginning.'
complete -c resize2fs -s M --description 'Shrink the file system to minimize its size as … [See Man Page]'
complete -c resize2fs -s p --description 'Prints out a percentage completion bars for eac… [See Man Page]'
complete -c resize2fs -s P --description 'Print an extimate of the number of file system … [See Man Page]'
complete -c resize2fs -s s --description 'Turns off the 64bit feature and frees blocks th… [See Man Page]'
complete -c resize2fs -s S --description 'The  resize2fs program will heuristically deter… [See Man Page]'
complete -c resize2fs -s z --description 'Before overwriting a file system block, write t… [See Man Page]'

