# sendiso
# Autogenerated from man page /usr/share/man/man1/sendiso.1.gz
# using Deroffing man parser
complete -c sendiso -s l -l loop --description 'Send dump file COUNT times.   Defaults to 1.'
complete -c sendiso -s i -l infinite --description 'Send dump file in an endless loop.'
complete -c sendiso -s s -l speed --description 'Send packets at speed SPEED, which can be given… [See Man Page]'
complete -c sendiso -s p -l port --description 'Choose port PORT for sending.'
complete -c sendiso -s h -l help --description 'Show help text and exit.'

