# sessreg
# Autogenerated from man page /usr/share/man/man1/sessreg.1.gz
# using Deroffing man parser
complete -c sessreg -s w --description 'This specifies an alternate wtmpx file, instead… [See Man Page]'
complete -c sessreg -s u --description 'This specifies an alternate utmpx file, instead… [See Man Page]'
complete -c sessreg -s L --description 'This specifies an alternate lastlog file, inste… [See Man Page]'
complete -c sessreg -s l --description 'This describes the "line" name of the entry.'
complete -c sessreg -s h --description 'This is set to indicate that the session was in… [See Man Page]'
complete -c sessreg -s s --description '\\" __BEGIN_UTMPX_ONLY__ This option is accepted… [See Man Page]'
complete -c sessreg -s x --description '\\" __BEGIN_UTMPX_ONLY__ This option is accepted… [See Man Page]'
complete -c sessreg -s t --description '\\" __BEGIN_UTMPX_ONLY__ This option is accepted… [See Man Page]'
complete -c sessreg -s V --description 'This option causes the command to print its version and exit.'
complete -c sessreg -s a --description 'This session should be added to utmpx/wtmpx.'
complete -c sessreg -s d --description 'This session should be deleted from utmpx/wtmpx.'

