# slminfo
# Autogenerated from man page /usr/share/man/man1/slminfo.1.gz
# using Type1
complete -c slminfo -s v -l verbose --description 'Turn on verbose mode, printing arpa format.'
complete -c slminfo -s p -l pr --description 'Prefer normal probability than -log(Pr) which is default.'

