# slmseg
# Autogenerated from man page /usr/share/man/man1/slmseg.1.gz
# using Type1
complete -c slmseg -s d --description 'Use dict_file as lexicon.'
complete -c slmseg -s f -l format --description 'Output Format, can be \'text\' or \'bin\'.  default \'bin\'.'
complete -c slmseg -s s -l stok --description 'Sentence token id.  Default 10.'
complete -c slmseg -s i -l show-id --description 'Show Id info.'

