# sndfile-info
# Autogenerated from man page /usr/share/man/man1/sndfile-info.1.gz
# using Darwin man parser
complete -c sndfile-info -l broadcast --description 'Display broadcast (BWF) info.'
complete -c sndfile-info -l cart --description 'Display the cart chunk of a WAV (or related) file.'
complete -c sndfile-info -l channel-map --description 'Display channel map.'
complete -c sndfile-info -l instrument --description 'Display instrument info: a base note, gain, vel… [See Man Page]'

