# sprof
# Autogenerated from man page /usr/share/man/man1/sprof.1.gz
# using Deroffing man parser
complete -c sprof -s c -l call-pairs --description 'Print a list of pairs of call paths for the int… [See Man Page]'
complete -c sprof -s p -l flat-profile --description 'Generate a flat profile of all of the functions… [See Man Page]'
complete -c sprof -s q -l graph --description 'Generate a call graph.'
complete -c sprof -s '?' -l help --description 'Display a summary of command-line options and a… [See Man Page]'
complete -c sprof -l usage --description 'Display a short usage message and exit.'
complete -c sprof -s V -l version --description 'Display the program version and exit.'
complete -c sprof -l --------------------------------------------- --description '                0. 00    0.'

