# systemd-resolve
# Autogenerated from man page /usr/share/man/man1/systemd-resolve.1.gz
# using Deroffing man parser
complete -c systemd-resolve -s 4 -s 6 --description 'By default, when resolving a hostname, both IPv… [See Man Page]'
complete -c systemd-resolve -s i -l interface --description 'Specifies the network interface to execute the query on.'
complete -c systemd-resolve -s p -l protocol --description 'Specifies the network protocol for the query.'
complete -c systemd-resolve -s t -l type -s c -l class --description 'Specifies the DNS resource record type (e. g.  A, AAAA, MX, .'
complete -c systemd-resolve -l service --description 'Enables service resolution.'
complete -c systemd-resolve -l service-address --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l service-txt --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l openpgp --description 'Enables OPENPGPKEY resource record resolution (see above).'
complete -c systemd-resolve -l tlsa --description 'Enables TLSA resource record resolution (see above).'
complete -c systemd-resolve -l cname --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l search --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l 'raw[' --description 'Dump the answer as binary data.'
complete -c systemd-resolve -l legend --description 'Takes a boolean parameter.'
complete -c systemd-resolve -l statistics --description 'If specified general resolver statistics are sh… [See Man Page]'
complete -c systemd-resolve -l reset-statistics --description 'Resets the statistics counters shown in --statistics to zero.'
complete -c systemd-resolve -l flush-caches --description 'Flushes all DNS resource record caches the serv… [See Man Page]'
complete -c systemd-resolve -l status --description 'Shows the global and per-link DNS settings in c… [See Man Page]'
complete -c systemd-resolve -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-resolve -l version --description 'Print a short version string and exit.'
complete -c systemd-resolve -l no-pager --description 'Do not pipe output into a pager.'

