# systemd-journal-gatewayd
# Autogenerated from man page /usr/share/man/man8/systemd-journal-gatewayd.service.8.gz
# using Deroffing man parser
complete -c systemd-journal-gatewayd -l cert --description 'Specify the path to a file containing a server … [See Man Page]'
complete -c systemd-journal-gatewayd -l key --description 'Specify the path to a file containing a server … [See Man Page]'
complete -c systemd-journal-gatewayd -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-journal-gatewayd -l version --description 'Print a short version string and exit.'

