# systemd-journal-remote
# Autogenerated from man page /usr/share/man/man8/systemd-journal-remote.8.gz
# using Deroffing man parser
complete -c systemd-journal-remote -l split-mode --description 'One of none or host.'
complete -c systemd-journal-remote -l compress -l no-compress --description 'Compress or not, respectively, the data in the … [See Man Page]'
complete -c systemd-journal-remote -l seal -l no-seal --description 'Periodically sign or not, respectively, the dat… [See Man Page]'
complete -c systemd-journal-remote -l getter -l option1 -l option2 --description 'Program to invoke to retrieve data.'
complete -c systemd-journal-remote -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-journal-remote -l version --description 'Print a short version string and exit.'
complete -c systemd-journal-remote -l url --description '.'
complete -c systemd-journal-remote -l listen-raw --description '.'
complete -c systemd-journal-remote -l listen-http -l listen-https --description '.'
complete -c systemd-journal-remote -l 'listen-https.' --description '/upload with "Content-Type: application/vnd. fdo.'
complete -c systemd-journal-remote -s n --description 'or.'
complete -c systemd-journal-remote -s o --description 'or.'
complete -c systemd-journal-remote -l output --description '.'
complete -c systemd-journal-remote -o HAccept: --description '.'
complete -c systemd-journal-remote -l header -o O- --description '.'

