# systemd-escape
# Autogenerated from man page /usr/share/man/man1/systemd-escape.1.gz
# using Deroffing man parser
complete -c systemd-escape -l suffix --description 'Appends the specified unit type suffix to the escaped string.'
complete -c systemd-escape -l template --description 'Inserts the escaped strings in a unit name template.'
complete -c systemd-escape -l path -s p --description 'When escaping or unescaping a string, assume it… [See Man Page]'
complete -c systemd-escape -l unescape --description 'Instead of escaping the specified strings, undo… [See Man Page]'
complete -c systemd-escape -l mangle --description 'Like --escape, but only escape characters that … [See Man Page]'
complete -c systemd-escape -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-escape -l version --description 'Print a short version string and exit.'
complete -c systemd-escape -l 'mangle.' --description '.'
complete -c systemd-escape -l escape --description '.'
complete -c systemd-escape -l 'unescape.' --description '.'

