# talk
# Autogenerated from man page /usr/share/man/man1/talk.1.gz
# using Deroffing man parser
complete -c talk -s '?' -l help --description 'give this help list.'
complete -c talk -l usage --description 'give a short usage message.'
complete -c talk -s V -l version --description 'print program version AUTHOR Written by Kipp Hi… [See Man Page]'

