# tc-xt
# Autogenerated from man page /usr/share/man/man8/tc-xt.8.gz
# using Deroffing man parser
complete -c tc-xt -s j --description 'Perform a jump to the given iptables target, op… [See Man Page]'

