# tc
# Autogenerated from man page /usr/share/man/man8/tc.8.gz
# using Deroffing man parser
complete -c tc -s b -s b -o batch -o batch --description 'read commands from provided file or standard in… [See Man Page]'
complete -c tc -o force --description 'don\'t terminate tc on errors in batch mode.'
complete -c tc -s n -o net -o netns --description 'switches  tc to the specified network namespace R NETNS .'
complete -c tc -o 's[tatistics]' --description '.'
complete -c tc -o 'd[etails]' --description '.'
complete -c tc -o 'r[aw]' --description '.'
complete -c tc -o 'p[retty]' --description '.'
complete -c tc -o 'i[ec]' --description '.'
complete -c tc -o 'g[raph]' --description '.'
complete -c tc -o 'n[etns]' --description 'help  }.'
complete -c tc -o cf -o conf --description 'specifies path to the config file.'
complete -c tc -o nm --description '.'
complete -c tc -s s -o stats -o statistics --description 'output more statistics about packet usage.'
complete -c tc -s d -o details --description 'output more detailed information about rates and cell sizes.'
complete -c tc -s r -o raw --description 'output raw hex values for handles.'
complete -c tc -s p -o pretty --description 'decode filter offset and mask values to equival… [See Man Page]'
complete -c tc -o iec --description 'print rates in IEC units (ie.  1K = 1024).'
complete -c tc -s g -o graph --description 'shows classes as ASCII graph.'
complete -c tc -o name --description 'resolve class name from /etc/iproute2/tc_cls fi… [See Man Page]'

