# tdbtool
# Autogenerated from man page /usr/share/man/man8/tdbtool.8.gz
# using Deroffing man parser
complete -c tdbtool -s l --description 'This options disables any locking, by passing T… [See Man Page]'

