# teamnl
# Autogenerated from man page /usr/share/man/man8/teamnl.8.gz
# using Deroffing man parser
complete -c teamnl -s h -l help --description 'Print help text to console and exit.'
complete -c teamnl -s p -l port_name --description 'Select per-port option of provided interface name.'
complete -c teamnl -s a -l array_index --description 'Select array option of provided array index.  COMMAND.'

