# teamd
# Autogenerated from man page /usr/share/man/man8/teamd.8.gz
# using Deroffing man parser
complete -c teamd -s h -l help --description 'Print help text to console and exit.'
complete -c teamd -s V -l version --description 'Print version information to console and exit.'
complete -c teamd -s d -l daemonize --description 'Daemonize after startup.'
complete -c teamd -s k -l kill --description 'Kill running daemon instance.'
complete -c teamd -s e -l check --description 'Return 0 if a daemon is already running.'
complete -c teamd -s f -l config-file --description 'Load the specified configuration file.'
complete -c teamd -s c -l config --description 'Use given JSON format configuration string.'
complete -c teamd -s p -l pid-file --description 'Use the specified PID file.'
complete -c teamd -s g -l debug --description 'Turns on debugging messages.'
complete -c teamd -s r -l force-recreate --description 'Force team device recreation in case it already exists.'
complete -c teamd -s o -l take-over --description 'Take over the device if it already exists.'
complete -c teamd -s N -l no-quit-destroy --description 'This option also ensures that the team device i… [See Man Page]'
complete -c teamd -s t -l team-dev --description 'Use the specified team device name (overrides "… [See Man Page]'
complete -c teamd -s n -l no-ports --description 'Start without ports, even if they are listed in… [See Man Page]'
complete -c teamd -s D -l dbus-enable --description 'Enable D-Bus interface.'
complete -c teamd -s Z -l zmq-enable --description 'Enable ZMQ interface.'
complete -c teamd -s U -l usock-enable --description 'Enable UNIX domain socket interface.'
complete -c teamd -s u -l usock-disable --description 'Disable UNIX domain socket interface.'

