# teamdctl
# Autogenerated from man page /usr/share/man/man8/teamdctl.8.gz
# using Deroffing man parser
complete -c teamdctl -s h -l help --description 'Print help text to console and exit.'
complete -c teamdctl -s v -l verbosity --description 'Increase output verbosity.'
complete -c teamdctl -s o -l oneline --description 'Force output to one line if possible.'
complete -c teamdctl -s D -l force-dbus --description 'Force to use D-Bus interface.'
complete -c teamdctl -s Z -l force-zmq --description 'Force to use ZMQ interface.'
complete -c teamdctl -s U -l force-usock --description 'Force to use UNIX domain socket interface.'

