# thin_rmap
# Autogenerated from man page /usr/share/man/man8/thin_rmap.8.gz
# using Deroffing man parser
complete -c thin_rmap -s h -l 'help.' --description 'Print help and exit.'
complete -c thin_rmap -s V -l 'version.' --description 'Output version information and exit.'

