# thin_delta
# Autogenerated from man page /usr/share/man/man8/thin_delta.8.gz
# using Deroffing man parser
complete -c thin_delta -l thin1 -l snap1 --description 'The numeric identifier for the first thin volume to diff.'
complete -c thin_delta -s m -l metadata-snap --description 'If you want to get information out of a live po… [See Man Page]'
complete -c thin_delta -l verbose --description 'Provide extra information on the mappings.'
complete -c thin_delta -s h -l help --description 'Print help and exit.'
complete -c thin_delta -s V -l version --description 'Output version information and exit.'

