# thin_trim
# Autogenerated from man page /usr/share/man/man8/thin_trim.8.gz
# using Deroffing man parser
complete -c thin_trim -l pool-inactive --description 'Indicates you are aware the pool should be inactive.'
complete -c thin_trim -s h -l help --description 'Print help and exit.'
complete -c thin_trim -s V -l version --description 'Output version information and exit.'

