# thin_metadata_size
# Autogenerated from man page /usr/share/man/man8/thin_metadata_size.8.gz
# using Deroffing man parser
complete -c thin_metadata_size -s b -l block-size --description 'Block size of thin provisioned devices in units… [See Man Page]'
complete -c thin_metadata_size -s s -l pool-size --description 'Thin provisioning pool size in units of bytes, … [See Man Page]'
complete -c thin_metadata_size -s m -l max-thins --description 'Maximum sum of all thin provisioned devices and snapshots.'
complete -c thin_metadata_size -s u -l unit --description 'Output unit specifier in units of bytes, sector… [See Man Page]'
complete -c thin_metadata_size -s n -l numeric-only --description 'Limit output to just the size number with the o… [See Man Page]'
complete -c thin_metadata_size -s h -l help --description 'Print help and exit.'
complete -c thin_metadata_size -s V -l version --description 'Output version information and exit.'

