# thin_ls
# Autogenerated from man page /usr/share/man/man8/thin_ls.8.gz
# using Deroffing man parser
complete -c thin_ls -s o -l format --description 'Give a comma separated list of the fields to be output.'
complete -c thin_ls -l no-headers --description 'Don\'t output headers.'
complete -c thin_ls -s m -l metadata-snap --description 'If you want to get information out of a live po… [See Man Page]'
complete -c thin_ls -l verbose --description 'Provide extra information on the mappings.'
complete -c thin_ls -s h -l help --description 'Print help and exit.'
complete -c thin_ls -s V -l version --description 'Output version information and exit.'

