# thin_dump
# Autogenerated from man page /usr/share/man/man8/thin_dump.8.gz
# using Deroffing man parser
complete -c thin_dump -s f -l format --description 'Print output in XML or human readable format.'
complete -c thin_dump -s r -l 'repair.' --description 'Repair the metadata whilst dumping it.'
complete -c thin_dump -s m -l metadata-snap --description 'Dump metadata snapshot created by device-mapper… [See Man Page]'
complete -c thin_dump -s h -l 'help.' --description 'Print help and exit.'
complete -c thin_dump -s V -l 'version.' --description 'Output version information and exit.'

