# tipc
# Autogenerated from man page /usr/share/man/man8/tipc.8.gz
# using Deroffing man parser
complete -c tipc -o 'h[help]' --description '.'
complete -c tipc -s h -l help --description 'Show help about last given command.'

