# tipc-bearer
# Autogenerated from man page /usr/share/man/man8/tipc-bearer.8.gz
# using Deroffing man parser
complete -c tipc-bearer -s h -l help --description 'Show help about last valid command.'

