# tipc-nametable
# Autogenerated from man page /usr/share/man/man8/tipc-nametable.8.gz
# using Deroffing man parser
complete -c tipc-nametable -s h -l help --description 'Show help about last valid command.'

