# tpmtool
# Autogenerated from man page /usr/share/man/man1/tpmtool.1.gz
# using Type1
complete -c tpmtool -o 'no-inder\\f[]' --description 'Use the DER format for keys.'
complete -c tpmtool -o 'no-outder\\f[]' --description 'Use DER format for output keys.'

