# tslmendian
# Autogenerated from man page /usr/share/man/man1/tslmendian.1.gz
# using Type1
complete -c tslmendian -s e --description 'Specify the output-lm-file\'s endian-ness.  It can be le or ge.'
complete -c tslmendian -s v --description 'Prints out the endian-ness of input-lm-file.'
complete -c tslmendian -s i --description 'Identify the input file of convert.'

