# tslminfo
# Autogenerated from man page /usr/share/man/man1/tslminfo.1.gz
# using Type1
complete -c tslminfo -s v -l verbose --description 'Turn on verbose mode, printing arpa format.'
complete -c tslminfo -s p -l pr --description 'Prefer normal probability than -log(Pr) which is default.'

