# ul
# Autogenerated from man page /usr/share/man/man1/ul.1.gz
# using Deroffing man parser
complete -c ul -s i -l indicated --description 'Underlining is indicated by a separate line con… [See Man Page]'
complete -c ul -s t -s T -l terminal --description 'Override the environment variable  TERM with th… [See Man Page]'
complete -c ul -s V -l version --description 'Display version information and exit.'
complete -c ul -s h -l help --description 'Display help text and exit.'

