# unshare
# Autogenerated from man page /usr/share/man/man1/unshare.1.gz
# using Deroffing man parser
complete -c unshare -s i -l ipc --description 'Unshare the IPC namespace.'
complete -c unshare -s m -l mount --description 'Unshare the mount namespace.'
complete -c unshare -s n -l net --description 'Unshare the network namespace.'
complete -c unshare -s p -l pid --description 'Unshare the PID namespace.'
complete -c unshare -s u -l uts --description 'Unshare the UTS namespace.'
complete -c unshare -s U -l user --description 'Unshare the user namespace.'
complete -c unshare -s C -l cgroup --description 'Unshare the cgroup namespace.'
complete -c unshare -s f -l fork --description 'Fork the specified program as a child process o… [See Man Page]'
complete -c unshare -l mount-proc --description 'Just before running the program, mount the proc… [See Man Page]'
complete -c unshare -s r -l map-root-user --description 'Run the program only after the current effectiv… [See Man Page]'
complete -c unshare -l propagation --description 'Recursively set the mount propagation flag in t… [See Man Page]'
complete -c unshare -l setgroups --description 'Allow or deny the  setgroups (2) syscall in a user namespace.'
complete -c unshare -s V -l version --description 'Display version information and exit.'
complete -c unshare -l 'cgroup[' --description 'Unshare the cgroup namespace.'
complete -c unshare -s h -l help --description 'Display help text and exit.  EXAMPLES.'

