# urxvtd
# Autogenerated from man page /usr/share/man/man1/urxvtd.1.gz
# using Type1
complete -c urxvtd -s q -l quiet --description 'Normally, urxvtd outputs the message \\f(CW\\*(C`… [See Man Page]'
complete -c urxvtd -s o -l opendisplay --description 'This forces urxvtd to open a connection to the … [See Man Page]'
complete -c urxvtd -s f -l fork --description 'This makes urxvtd fork after it has bound itsel… [See Man Page]'
complete -c urxvtd -s m -l mlock --description 'This makes urxvtd call mlockall\\|(2) on itself.'

