# vedit
# Autogenerated from man page /usr/share/man/man1/vedit.1.gz
# using Deroffing man parser
complete -c vedit -o ccommand --description 'Execute  command when editing begins.'
complete -c vedit -s l --description 'Start in a special mode useful for the  Lisp pr… [See Man Page]'
complete -c vedit -o 'r[filename]' -s L --description 'When no argument is supplied with this option, … [See Man Page]'
complete -c vedit -s R --description 'Files are opened read-only when this option is given.'
complete -c vedit -s s --description 'Script mode; all feedback for interactive editing is disabled.'
complete -c vedit -s t --description 'Read the  tags file, then choose the file and p… [See Man Page]'
complete -c vedit -s V --description 'Echo command input to standard error, unless it… [See Man Page]'
complete -c vedit -s w --description 'Specify the size of the editing window for visual mode.'
complete -c vedit -s c --description 'Execute command when editing begins.'
complete -c vedit -s r --description 'When no argument is supplied with this option, … [See Man Page]'

