# vfychain
# Autogenerated from man page /usr/share/man/man1/vfychain.1.gz
# using Deroffing man parser
complete -c vfychain -s a --description 'the following certfile is base64 encoded.'
complete -c vfychain -s b --description 'Validate date (default: now).'
complete -c vfychain -s d --description 'database directory.'
complete -c vfychain -s f --description 'Enable cert fetching from AIA URL.'
complete -c vfychain -s o --description 'Set policy OID for cert validation(Format OID. 1. 2. 3).'
complete -c vfychain -s p --description 'Use PKIX Library to validate certificate by calling: .'
complete -c vfychain -s r --description 'Following certfile is raw binary DER (default).'
complete -c vfychain -s t --description 'Following cert is explicitly trusted (overrides db trust).'
complete -c vfychain -s u --description '0=SSL client, 1=SSL server, 2=SSL StepUp, 3=SSL… [See Man Page]'
complete -c vfychain -s T --description 'Trust both explicit trust anchors (-t) and the database.'
complete -c vfychain -s v --description 'Verbose mode.'
complete -c vfychain -s w --description 'Database password.'
complete -c vfychain -s W --description 'Password file.'
complete -c vfychain -s g --description 'Sets status checking test type.'
complete -c vfychain -s h --description 'Sets revocation flags for the test type it follows.'
complete -c vfychain -s m --description 'Sets method type for the test type it follows.'
complete -c vfychain -s s --description 'Sets revocation flags for the method it follows.'

