# xcmsdb
# Autogenerated from man page /usr/share/man/man1/xcmsdb.1.gz
# using Type1
complete -c xcmsdb -o query --description 'This option attempts to read the XDCCC properti… [See Man Page]'
complete -c xcmsdb -o remove --description 'This option attempts to remove the XDCCC proper… [See Man Page]'
complete -c xcmsdb -o 'format\\032' --description 'Specifies the property format (32, 16, or 8 bit… [See Man Page]'
complete -c xcmsdb -o help --description 'This option prints a summary of the available o… [See Man Page]'

