# zipcmp
# Autogenerated from man page /usr/share/man/man1/zipcmp.1.gz
# using Deroffing man parser
complete -c zipcmp -s h --description 'Display a short help message and exit.'
complete -c zipcmp -s i --description 'Compare names ignoring case distinctions.'
complete -c zipcmp -s p --description 'Enable paranoid checks.'
complete -c zipcmp -s q --description 'Quiet mode.  Compare.'
complete -c zipcmp -o 'v.' --description '.'
complete -c zipcmp -s t --description 'Test zip files by comparing the contents to their checksums.'
complete -c zipcmp -s V --description 'Display version information and exit.'
complete -c zipcmp -s v --description 'Verbose mode.  Print details about differences to stdout.'

