# zipmerge
# Autogenerated from man page /usr/share/man/man1/zipmerge.1.gz
# using Deroffing man parser
complete -c zipmerge -s D --description 'Ignore directory components in file name comparisons.'
complete -c zipmerge -s h --description 'Display a short help message and exit.'
complete -c zipmerge -s I --description 'Ignore case in file name comparisons.'
complete -c zipmerge -s i --description 'Ask before overwriting files.  See also.'
complete -c zipmerge -o 's.' --description '.'
complete -c zipmerge -s S --description 'Do not overwrite files that have the same size … [See Man Page]'
complete -c zipmerge -s s --description 'When.'
complete -c zipmerge -s V --description 'Display version information and exit.'

