# zresample
# Autogenerated from man page /usr/share/man/man1/zresample.1.gz
# using Deroffing man parser
complete -c zresample -l help --description 'Display a short help text.'
complete -c zresample -l rate --description 'Set the output sample rate.'
complete -c zresample -l wav --description 'Produce a WAV file, or for more than 2 channels, a WAVEX file.'
complete -c zresample -l amb --description 'Produce a WAVEX file with the Ambisonic GUID.'
complete -c zresample -l caf --description 'Produce a Core Audio file. SS Output sample format.'
complete -c zresample -l 16bit --description 'Output sample format is signed 16-bit.'
complete -c zresample -l 24bit --description 'Output sample format is 24-bit.  This is the default.'
complete -c zresample -l float --description 'Output sample format is 32-bit floating point. SS Dithering.'
complete -c zresample -l rec --description 'Add white dithering noise with a rectangular distribution.'
complete -c zresample -l tri --description 'Add filtered noise with a triangular distribution.'
complete -c zresample -l lips --description 'This uses the optimal error feedback filter des… [See Man Page]'
complete -c zresample -l pad --description 'Insert zero valued input samples at the start a… [See Man Page]'

