# zretune
# Autogenerated from man page /usr/share/man/man1/zretune.1.gz
# using Deroffing man parser
complete -c zretune -l help --description 'Display a short help text.'
complete -c zretune -l cent --description 'The number of cents by which the pitch is changed.'
complete -c zretune -l wav --description 'Produce a WAV file, or for more than 2 channels, a WAVEX file.'
complete -c zretune -l amb --description 'Produce a WAVEX file with the Ambisonic GUID.'
complete -c zretune -l caf --description 'Produce a Core Audio file. SS Output sample format.'
complete -c zretune -l 16bit --description 'Output sample format is signed 16-bit.'
complete -c zretune -l 24bit --description 'Output sample format is 24-bit.  This is the default.'
complete -c zretune -l float --description 'Output sample format is 32-bit floating point. SS Dithering.'
complete -c zretune -l rec --description 'Add white dithering noise with a rectangular distribution.'
complete -c zretune -l tri --description 'Add filtered noise with a triangular distribution.'
complete -c zretune -l lips --description 'This uses the optimal error feedback filter des… [See Man Page]'
complete -c zretune -l pad --description 'Insert zero valued input samples at the start a… [See Man Page]'

